drop table if exists tb_address cascade;
create table tb_address (
    cod_address bigint generated by default as identity primary key,
    txt_cep varchar(255),
    txt_logradouro varchar(255),
    txt_complemento varchar(255),
    txt_bairro bigint,
    txt_localidade varchar(255),
    txt_uf varchar(255),
    txt_ddd varchar(255),
    user_cod_user bigint
);