drop table if exists tb_product cascade;
create table tb_product (
    cod_product bigint generated by default as identity primary key,
    txt_name varchar(255),
    txt_description varchar(255),
    dou_price double precision ,
    txt_img varchar(255)
);