drop table if exists tb_order cascade;
create table tb_order (
    cod_order bigint generated by default as identity primary key,
    ist_date date,
    cod_status bigint ,
    user_cod_user bigint
);